// Run before build: scans public/images/ and public/photos/ for date-named files,
// sorts by date, writes src/data/photos.ts
const fs   = require('fs')
const path = require('path')

const OUT_FILE = path.join(__dirname, '../src/data/photos.ts')

const MONTHS = ['January','February','March','April','May','June',
                'July','August','September','October','November','December']

function toLabel(y, m, d) {
  return `${MONTHS[parseInt(m, 10) - 1]} ${parseInt(d, 10)}, ${y}`
}

const base = process.env.NEXT_PUBLIC_BASE_PATH ?? ''

// ── Scan public/images/ — format YYYYMMDD_HHMMSS.jpg ──────────────────────────
const IMAGES_RE = /^(\d{4})(\d{2})(\d{2})_\d{6}/
const IMG_EXT   = /\.(jpe?g|png|webp|avif)$/i

const imagesDir = path.join(__dirname, '../public/images')
const imageEntries = fs.existsSync(imagesDir)
  ? fs.readdirSync(imagesDir)
      .filter(f => IMAGES_RE.test(f) && IMG_EXT.test(f))
      .map(f => {
        const [, y, m, d] = IMAGES_RE.exec(f)
        return { src: `${base}/images/${f}`, date: `${y}-${m}-${d}`, label: toLabel(y, m, d), _sort: f }
      })
  : []

// ── Scan public/photos/ — format YYYY-MM-DD*.jpg ──────────────────────────────
const PHOTOS_RE = /^(\d{4})-(\d{2})-(\d{2})/

const photosDir = path.join(__dirname, '../public/photos')
if (!fs.existsSync(photosDir)) fs.mkdirSync(photosDir, { recursive: true })

const photoEntries = fs.readdirSync(photosDir)
  .filter(f => PHOTOS_RE.test(f) && IMG_EXT.test(f))
  .map(f => {
    const [, y, m, d] = PHOTOS_RE.exec(f)
    return { src: `${base}/photos/${f}`, date: `${y}-${m}-${d}`, label: toLabel(y, m, d), _sort: f }
  })

// ── Merge, sort by date (then filename for same-day ties), strip _sort ─────────
const all = [...imageEntries, ...photoEntries]
  .sort((a, b) => a.date.localeCompare(b.date) || a._sort.localeCompare(b._sort))
  .map(({ src, date, label }) => ({ src, date, label }))

const content =
  `// Auto-generated by scripts/gen-photos.js — do not edit by hand\n\n` +
  `export interface Photo {\n  src: string\n  date: string\n  label: string\n}\n\n` +
  `export const photos: Photo[] = ${JSON.stringify(all, null, 2)}\n`

fs.writeFileSync(OUT_FILE, content)
console.log(`gen-photos: wrote ${all.length} photo(s) → src/data/photos.ts`)
