// Run before build: scans public/photos/, sorts by date in filename, writes src/data/photos.ts
const fs = require('fs')
const path = require('path')

const PHOTOS_DIR = path.join(__dirname, '../public/photos')
const OUT_FILE   = path.join(__dirname, '../src/data/photos.ts')
const DATE_RE    = /^(\d{4})-(\d{2})-(\d{2})/
const IMG_RE     = /\.(jpe?g|png|webp|avif)$/i

const MONTHS = ['January','February','March','April','May','June',
                'July','August','September','October','November','December']

function toLabel(y, m, d) {
  return `${MONTHS[parseInt(m, 10) - 1]} ${parseInt(d, 10)}, ${y}`
}

if (!fs.existsSync(PHOTOS_DIR)) fs.mkdirSync(PHOTOS_DIR, { recursive: true })

const base  = process.env.NEXT_PUBLIC_BASE_PATH ?? ''

const files = fs.readdirSync(PHOTOS_DIR)
  .filter(f => DATE_RE.test(f) && IMG_RE.test(f))
  .sort()   // YYYY-MM-DD prefix sorts lexicographically = chronologically

const photos = files.map(f => {
  const [, y, m, d] = DATE_RE.exec(f)
  return {
    src:   `${base}/photos/${f}`,
    date:  `${y}-${m}-${d}`,
    label: toLabel(y, m, d),
  }
})

const content =
  `// Auto-generated by scripts/gen-photos.js — do not edit by hand\n` +
  `export const photos = ${JSON.stringify(photos, null, 2)} as const\n\n` +
  `export type Photo = (typeof photos)[number]\n`

fs.writeFileSync(OUT_FILE, content)
console.log(`gen-photos: wrote ${photos.length} photo(s) → src/data/photos.ts`)
